package hu.kniznertamas.mavenhibernate.entity;
// Generated 2016.02.23. 12:35:25 by Hibernate Tools 4.3.1

/**
 * Actors generated by hbm2java
 */
public class Actors implements java.io.Serializable {

    private Integer id;
    private String name;

    public Actors() {
    }

    public Actors(String name) {
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
