package hu.kniznertamas.mavenhibernate.entity;
// Generated 2016.02.23. 12:35:25 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Movies generated by hbm2java
 */
public class Movies implements java.io.Serializable {

    private Integer id;
    private String title;
    private Date premiere;

    public Movies() {
    }

    public Movies(String title, Date premiere) {
        this.title = title;
        this.premiere = premiere;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getPremiere() {
        return this.premiere;
    }

    public void setPremiere(Date premiere) {
        this.premiere = premiere;
    }

}
