package hu.kniznertamas.mavenhibernate.entity;
// Generated 2016.02.23. 12:35:25 by Hibernate Tools 4.3.1

/**
 * MovieActors generated by hbm2java
 */
public class MovieActors implements java.io.Serializable {

    private Integer id;
    private int actorId;
    private int movieId;

    public MovieActors() {
    }

    public MovieActors(int actorId, int movieId) {
        this.actorId = actorId;
        this.movieId = movieId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getActorId() {
        return this.actorId;
    }

    public void setActorId(int actorId) {
        this.actorId = actorId;
    }

    public int getMovieId() {
        return this.movieId;
    }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }

}
